paths:
  uploads: uploads
  data: content
collections_config:
  projects:
    path: content/teachers
    output: false
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  services:
    path: content/services
    output: false
    url:
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_enabled_editors:
  - visual
  - content
  - data
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    italic: true
  block:
    allow_custom_markup: false
    remove_custom_markup: false
    format: p h3
    image_size_attributes: true
    redo: true
    undo: true
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: align-center
    code: true
    copyformatting: true
    embed: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify: align-justify
    left: align-left
    link: true
    numberedlist: true
    outdent: true
    redo: true
    removeformat: true
    right: align-right
    snippet: true
    strike: true
    styles: /css/editor.css
    subscript: true
    superscript: true
    table: true
    underline: true
    undo: true
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
